# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, null=True)),
                ('visivel', models.BooleanField(verbose_name=True)),
                ('tipo', models.CharField(max_length=200, null=True)),
                ('institucional', models.BooleanField(verbose_name=True)),
                ('participantes', models.ManyToManyField(related_name='item_participantes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dataI', models.DateTimeField(blank=True, null=True)),
                ('dataF', models.DateTimeField(blank=True, null=True)),
                ('agendas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='agendas.Agenda')),
            ],
        ),
    ]
