# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_convite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convite',
            old_name='receiver',
            new_name='convidado',
        ),
        migrations.RenameField(
            model_name='convite',
            old_name='sender',
            new_name='realizador',
        ),
        migrations.RemoveField(
            model_name='convite',
            name='answer',
        ),
        migrations.AddField(
            model_name='convite',
            name='resposta',
            field=models.BooleanField(default=False, verbose_name='Aceito'),
        ),
    ]
